* Alter make test command to dump coveragedata * Alter e2e commands to dump coveragedata * Integrate run with coverage in CI * Combine coverage reports * Fail on coverage below 80
Signed-off-by: portly-halicore-76 <170707699+portly-halicore-76@users.noreply.github.com>

diff --git a/.github/workflows/ci-run-on-pr.yaml b/.github/workflows/ci-run-on-pr.yaml
--- a/.github/workflows/ci-run-on-pr.yaml
+++ b/.github/workflows/ci-run-on-pr.yaml
@@ -17,7 +17,7 @@ jobs:
     steps:
       - name: Fails in order to indicate that pull request needs to be marked as ready to review and other checks needs to pass.
         run: exit 1
-
+  
   codechanges:
     if: ${{ github.event.pull_request.draft == false }}
     runs-on: ubuntu-22.04
@@ -35,7 +35,7 @@ jobs:
               - go.sum
               - '**.go'
               - '.github/workflows/ci-build.yaml'
-
+  
   check-go:
     name: Ensure Go modules synchronicity
     runs-on: ubuntu-22.04
@@ -56,7 +56,7 @@ jobs:
         run: |
           go mod tidy
           git diff --exit-code -- .
-
+  
   lint-go:
     name: Lint Go code
     runs-on: ubuntu-22.04
@@ -78,7 +78,7 @@ jobs:
         with:
           version: v1.60.3
           args: --verbose
-
+  
   code-gen:
     name: Check generated code
     runs-on: ubuntu-22.04
@@ -93,7 +93,7 @@ jobs:
           make manifests
           make generate
           git diff --exit-code -- .
-
+  
   unit-test:
     name: Run unit tests
     runs-on: ubuntu-22.04
@@ -109,7 +109,12 @@ jobs:
           go-version: ${{ env.GOLANG_VERSION }}
       - name: Test
         run: make test
- 
+      - name: Generate test results artifacts
+        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
+        with:
+          name: unittests-coverage
+          path: /tmp/coverage/unittests
+  
   e2e-test:
     name: Run e2e tests
     runs-on: ubuntu-22.04
@@ -145,7 +150,7 @@ jobs:
         timeout-minutes: 5
         run: |
           set -x
-          make start-e2e 2>&1 | sed -r "s/[[:cntrl:]]\[[0-9]{1,3}m//g" > /tmp/e2e-server.log &
+          make start-e2e E2E_WITH_COVERAGE=true 2>&1 | sed -r "s/[[:cntrl:]]\[[0-9]{1,3}m//g" > /tmp/e2e-server.log &
           count=1
           until curl -f http://127.0.0.1:8081/healthz; do
             sleep 10;
@@ -161,13 +166,18 @@ jobs:
           set -x
           make test-e2e
           killall goreman run stop-all || echo "trouble killing goreman"
+      - name: Upload e2e coverage report
+        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
+        with:
+          name: e2e-code-coverage
+          path: /tmp/coverage/paas
       - name: Upload operator deployment log on failure
         uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
         with:
           name: e2e-operator-logs-${{ github.run_id }}.log
           path: /tmp/e2e-server.log
         if: ${{ failure() }}
-
+  
   e2e-test-with-built-image:
     name: Run e2e tests against deployed image
     runs-on: ubuntu-22.04
@@ -226,3 +236,41 @@ jobs:
         if: ${{ failure() }}
       - name: Clean test fixtures
         run: rm -rf /tmp/paas-e2e
+  
+  analyze:
+    name: Process & analyze test artifacts
+    if: ${{ needs.codechanges.outputs.backend == 'true' && github.event.pull_request.draft == false}}
+    runs-on: ubuntu-22.04
+    needs:
+      - unit-test
+      - codechanges
+      - e2e-test
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@8410ad0602e1e429cee44a835ae9f77f654a6694 # v4.0.0
+      - name: Get e2e code coverage
+        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
+        with:
+          name: e2e-code-coverage
+          path: e2e-code-coverage
+      - name: Get unit test code coverage
+        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
+        with:
+          name: unittests-coverage
+          path: test-results
+      - name: Combine coverage reports
+        run: go tool covdata textfmt -i=test-results,e2e-code-coverage -o test-results/full-coverage
+      - name: Generate and print report
+        run: go tool cover -func test-results/full-coverage
+      - name: Upload test-coverage artifact
+        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
+        with:
+          name: full-coverage-report
+          path: test-results/full-coverage
+      - name: Fail if code coverage < 80%
+        run: |
+          coverage=$(go tool cover -func test-results/full-coverage | grep "total:" | awk '{print $NF}' | cut -d'%' -f1)
+          if [ "$(echo "$coverage < 80" | bc)" -eq 1 ]; then
+            echo "Coverage is less than 80% ($coverage%). Failing the build."
+            exit 1
+          fi
